In [29]:
import random

import pandas as pd
import numpy as np

import seaborn as sns
import matplotlib.pyplot as plt

In [38]:
# Read in and merge data
csv_data = pd.read_csv('../02_processed_data/combined_csv_data.csv')
json_data = pd.read_csv('../02_processed_data/combined_json_data.csv')
all_data = pd.concat([csv_data, json_data])
all_data.drop(['prolificId', 'questionId', 'trialIndex', 'question'], axis=1, inplace=True)

In [56]:
pids_to_handle = []
clean_data = pd.DataFrame()
for pid in all_data['participantId'].unique():
    try:
        pid_df = all_data[all_data['participantId'] == pid]
        fixed_choices = pid_df[pid_df['eventType'] == 'fixedChoice']
        disc_trials = pid_df[pid_df['eventType'] == 'discountingTrial']
        for task in disc_trials['taskLabel'].unique():
            task_df = disc_trials[disc_trials['taskLabel'] == task]
            task_df = task_df.drop_duplicates(subset=['probability', 'indifferencePoint']).reset_index(drop=True)
            task_df = task_df.sort_values(by='indifferencePoint', ascending=False)
            task_df['probability'] = [1.00, 0.75, 0.50, 0.20, 0.05]
        pid_df = pd.concat([fixed_choices, task_df]).reset_index(drop=True)
        clean_data = pd.concat([clean_data, pid_df])
    except:
        pids_to_handle.append(pid)

clean_data.reset_index(drop=True)

,participantId,eventType,optionA,optionB,choice,taskLabel,probability,certainAmount,indifferencePoint
0,P426866,fixedChoice,30% Chance of $66,100% Chance of $20,B,money,0.30,20.0,NaN
1,P426866,fixedChoice,85% Chance of $66,100% Chance of $56,A,money,0.85,56.0,NaN
2,P426866,fixedChoice,30% Chance of $33,100% Chance of $10,B,money,0.30,10.0,NaN
3,P426866,fixedChoice,60% Chance of $33 worth of steak,100% Chance of $10 worth of steak,A,steak,0.60,10.0,NaN
4,P426866,fixedChoice,60% Chance of $33,100% Chance of $10,B,money,0.60,10.0,NaN
...,...,...,...,...,...,...,...,...,...
401,P648615,discountingTrial,eggrolls5,50% chance of eggrolls10,probabilistic,eggrolls10 Discounting,1.00,5.0,9.84375
402,P648615,discountingTrial,eggrolls5,5% chance of eggrolls10,probabilistic,eggrolls10 Discounting,0.75,5.0,9.84375
403,P648615,discountingTrial,eggrolls5,20% chance of eggrolls10,probabilistic,eggrolls10 Discounting,0.50,5.0,9.84375
404,P648615,discountingTrial,eggrolls5,75% chance of eggrolls10,certain,eggrolls10 Discounting,0.20,5.0,2.34375
405,P648615,discountingTrial,eggrolls5,100% chance of eggrolls10,certain,eggrolls10 Discounting,0.05,5.0,2.03125

In [69]:
clean_data[clean_data['eventType']=='discountingTrial']['taskLabel'].unique()

array(['steak100 Discounting', '$10 Discounting',
       'burger and fries10 Discounting', 'pizza10 Discounting',
       '$100 Discounting', 'italian10 Discounting',
       'sushi100 Discounting', 'french fries10 Discounting',
       'Indian food10 Discounting', 'eggrolls10 Discounting'],
      dtype=object)

In [84]:
pids_to_handle = []
clean_data_2 = pd.DataFrame()
for pid in pids_to_handle[:1]:
    pid_df = all_data[all_data['participantId']==pid].reset_index(drop=True)
    for val in list(range(len(pid_df))):
        if pid_df['eventType'][val]=='fixedChoice':
            try: 
                int_true = int(pid_df['optionA'][val][-2:])
                pid_df['taskLabel'][val]="money"
            except:
                pid_df['taskLabel'][val]=pid_df['optionA'][val].split(" ")[-1]
                
        elif pid_df['eventType'][val]=='discountingTrial':
            print(pid_df['eventType'][val])
            # option = pid_df['optionA'][val].split(" ")[-1]
            # pid_df['taskLabel'][val] = option + " Discounting"



#     try:
#         fixed_choices = pid_df[pid_df['eventType'] == 'fixedChoice']
#         disc_trials = pid_df[pid_df['eventType'] == 'discountingTrial']
#         for task in disc_trials['taskLabel'].unique():
#             task_df = disc_trials[disc_trials['taskLabel'] == task]
#             task_df = task_df.drop_duplicates(subset=['probability', 'indifferencePoint']).reset_index(drop=True)
#             task_df = task_df.sort_values(by='indifferencePoint', ascending=False)
#             task_df['probability'] = [1.00, 0.75, 0.50, 0.20, 0.05]
#         pid_df = pd.concat([fixed_choices, task_df]).reset_index(drop=True)
#         clean_data_2 = pd.concat([clean_data_2, pid_df])
#     except:
#         pids_to_handle.append(pid)

# clean_data.reset_index(drop=True)

In [54]:
pid_df = all_data[all_data['participantId'] == 'P946654']
fixed_choices = pid_df[pid_df['eventType'] == 'fixedChoice']
disc_trials = pid_df[pid_df['eventType'] == 'discountingTrial']
    
for task in disc_trials['taskLabel'].unique():
    print(task)
    task_df = disc_trials[disc_trials['taskLabel'] == task]
    task_df = task_df.drop_duplicates(subset=['probability', 'indifferencePoint']).reset_index(drop=True)
    task_df = task_df.sort_values(by='indifferencePoint', ascending=False)
    task_df['probability'] = [1.00, 0.75, 0.50, 0.20, 0.05]
    print(task_df[['participantId', 'taskLabel', 'probability', 'indifferencePoint']], "\n\n")

discounting

ValueError: Length of values (5) does not match length of index (19)

In [40]:
fixed_choices

,participantId,eventType,optionA,optionB,choice,taskLabel,probability,certainAmount,indifferencePoint
1276,P738200,fixedChoice,60% Chance of $33,100% Chance of $28,B,money,0.60,28.0,NaN
1277,P738200,fixedChoice,60% Chance of $66,100% Chance of $56,B,money,0.60,56.0,NaN
1278,P738200,fixedChoice,30% Chance of $33,100% Chance of $10,A,money,0.30,10.0,NaN
1279,P738200,fixedChoice,60% Chance of $33,100% Chance of $10,A,money,0.60,10.0,NaN
1280,P738200,fixedChoice,85% Chance of $33,100% Chance of $28,B,money,0.85,28.0,NaN
1281,P738200,fixedChoice,30% Chance of $33,100% Chance of $28,B,money,0.30,28.0,NaN
1282,P738200,fixedChoice,85% Chance of $33,100% Chance of $10,A,money,0.85,10.0,NaN
1283,P738200,fixedChoice,85% Chance of $66,100% Chance of $56,A,money,0.85,56.0,NaN
1284,P738200,fixedChoice,30% Chance of $66,100% Chance of $20,B,money,0.30,20.0,NaN
1285,P738200,fixedChoice,30% Chance of $66,100% Chance of $56,B,money,0.30,56.0,NaN
1286,P738200,fixedChoice,85% Chance of $66,100% Chance of $20,A,money,0.85,20.0,NaN
1287,P738200,fixedChoice,60% Chance of $66,100% Chance of $20,A,money,0.60,20.0,NaN
1288,P738200,fixedChoice,60% Chance of $33 worth of Pizza,100% Chance of $28 worth of Pizza,B,Pizza,0.60,28.0,NaN
1289,P738200,fixedChoice,85% Chance of $33 worth of Pizza,100% Chance of $28 worth of Pizza,A,Pizza,0.85,28.0,NaN
1290,P738200,fixedChoice,85% Chance of $33 worth of Pizza,100% Chance of $10 worth of Pizza,A,Pizza,0.85,10.0,NaN
1291,P738200,fixedChoice,30% Chance of $33 worth of Pizza,100% Chance of $28 worth of Pizza,B,Pizza,0.30,28.0,NaN
1292,P738200,fixedChoice,30% Chance of $66 worth of Pizza,100% Chance of $56 worth of Pizza,B,Pizza,0.30,56.0,NaN
1293,P738200,fixedChoice,30% Chance of $66 worth of Pizza,100% Chance of $20 worth of Pizza,B,Pizza,0.30,20.0,NaN
1294,P738200,fixedChoice,60% Chance of $33 worth of Pizza,100% Chance of $10 worth of Pizza,A,Pizza,0.60,10.0,NaN
1295,P738200,fixedChoice,30% Chance of $33 worth of Pizza,100% Chance of $10 worth of Pizza,A,Pizza,0.30,10.0,NaN
1296,P738200,fixedChoice,85% Chance of $66 worth of Pizza,100% Chance of $56 worth of Pizza,A,Pizza,0.85,56.0,NaN
1297,P738200,fixedChoice,60% Chance of $66 worth of Pizza,100% Chance of $56 worth of Pizza,B,Pizza,0.60,56.0,NaN
1298,P738200,fixedChoice,60% Chance of $66 worth of Pizza,100% Chance of $20 worth of Pizza,A,Pizza,0.60,20.0,NaN
1299,P738200,fixedChoice,85% Chance of $66 worth of Pizza,100% Chance of $20 worth of Pizza,A,Pizza,0.85,20.0,NaN